name: .NET Publish and Deploy

on:
  push:
    branches:
      - $default-branch

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    # use release mode for all steps
    env:
      config: 'Release'
      registry: ${{ secrets.NEBULA_CONTAINERREGISTRY }} # Organization level
      image-name: ${{ secrets.DOCKER_IMAGE_NAME }} # Repository level
      app-name: ${{ secrets.APP_NAME }} # Repository level
      azure-credentials: ${{ secrets.INFRA_AZURE_CREDENTIALS }} # Organization level
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Repository level

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          creds: ${{ env.azure-credentials }}

      - name: Build and Push Docker Image
        run: az acr build -t ${{ env.registry }}/${{ env.image-name }}:latest -t ${{ env.registry }}/${{ env.image-name }}:${{ github.run_number }} -r ${{ env.registry }} .

      - name: Deploy to Dev/QA
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.app-name }}
          publish-profile: ${{ env.publish-profile }}
          images: '${{ env.registry }}/${{ env.image-name }}:${{ github.run_number }}'