name: .NET Publish and Deploy

on:
  push:
    branches:
      - $default-branch

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    # use release mode for all steps
    env:
      config: 'Release'
      registry: ${{ secrets.DEFAULT_CONTAINER_REGISTRY }}
      image-name: ${{ secrets.DOCKER_IMAGE_NAME }}
      image-tag: latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Docker Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registry }}
        username: ${{ secrets.DEFAULT_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.DEFAULT_CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and Push Docker Image to Docker Container Registry
      run: |
        docker build . -t ${{ env.registry }}/${{ env.image-name }}:${{ env.image-tag }}
        docker push ${{ env.registry }}/${{ env.image-name }}:${{ env.image-tag }}

    - name: Deploy to Dev/QA
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.APP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ env.registry }}/${{ env.image-name }}:${{ env.image-tag }}'
